# Generated by Django 5.0.13 on 2025-03-31 20:21

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analises',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_analise', models.CharField(max_length=64)),
                ('DataConsulta', models.DateTimeField()),
                ('Request', models.TextField()),
                ('Response', models.TextField()),
            ],
            options={
                'db_table': 'Analises',
            },
        ),
        migrations.CreateModel(
            name='BlackListCNAE',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('idCNAE', models.CharField(max_length=10)),
                ('Descricao', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'BlackListCNAE',
            },
        ),
        migrations.CreateModel(
            name='CnaeDivisao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
            ],
            options={
                'db_table': 'CnaeDivisoes',
            },
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_consulta', models.CharField(blank=True, max_length=64, null=True)),
                ('id_analise', models.CharField(blank=True, max_length=64, null=True)),
                ('DataConsulta', models.DateTimeField(blank=True, null=True)),
                ('Bureau', models.CharField(blank=True, max_length=255, null=True)),
                ('Request', models.TextField(blank=True, null=True)),
                ('Response', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Consultas',
            },
        ),
        migrations.CreateModel(
            name='EnriquecimentoCNAECedentesOpera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodCedente', models.CharField(blank=True, max_length=255, null=True)),
                ('NomeCedente', models.CharField(blank=True, max_length=255, null=True)),
                ('CNPJCedente', models.CharField(blank=True, max_length=255, null=True)),
                ('ID_SubClasse', models.CharField(blank=True, max_length=255, null=True)),
                ('Desc_SubClasse', models.CharField(blank=True, max_length=255, null=True)),
                ('ID_Classe', models.CharField(blank=True, max_length=255, null=True)),
                ('Desc_Classe', models.CharField(blank=True, max_length=255, null=True)),
                ('ID_Grupo', models.CharField(blank=True, max_length=255, null=True)),
                ('Desc_Grupo', models.CharField(blank=True, max_length=255, null=True)),
                ('ID_Divisao', models.CharField(blank=True, max_length=255, null=True)),
                ('Desc_Divisao', models.CharField(blank=True, max_length=255, null=True)),
                ('ID_Secao', models.CharField(blank=True, max_length=255, null=True)),
                ('Desc_Secao', models.CharField(blank=True, max_length=255, null=True)),
                ('Primario', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'EnriquecimentoCNAECedentesOpera',
            },
        ),
        migrations.CreateModel(
            name='ProspecSERASA',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_consulta', models.CharField(max_length=64)),
                ('CNPJ', models.CharField(blank=True, max_length=255, null=True)),
                ('RazaoSocial', models.CharField(blank=True, max_length=255, null=True)),
                ('NomeFant', models.CharField(blank=True, max_length=255, null=True)),
                ('Endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('Bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('Cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('UF', models.CharField(blank=True, max_length=255, null=True)),
                ('CEP', models.CharField(blank=True, max_length=255, null=True)),
                ('eMail', models.CharField(blank=True, max_length=255, null=True)),
                ('DDD', models.CharField(blank=True, max_length=255, null=True)),
                ('Telefone', models.CharField(blank=True, max_length=255, null=True)),
                ('DataFundacao', models.CharField(blank=True, max_length=255, null=True)),
                ('Ramo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ProspecSERASA',
            },
        ),
        migrations.CreateModel(
            name='Relatorios',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_consulta', models.CharField(blank=True, max_length=64, null=True)),
                ('id_analise', models.CharField(blank=True, max_length=64, null=True)),
                ('Data', models.DateTimeField(blank=True, null=True)),
                ('CNPJ', models.CharField(blank=True, max_length=255, null=True)),
                ('Relatorio', models.TextField(blank=True, null=True)),
                ('RelatorioPDF', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
            options={
                'db_table': 'Relatorios',
            },
        ),
        migrations.CreateModel(
            name='CnaeSecao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
            ],
            options={
                'db_table': 'CnaeSecoes',
                'indexes': [models.Index(fields=['id'], name='CnaeSecoes_id_b8aaa6_idx')],
            },
        ),
        migrations.CreateModel(
            name='CnaeGrupo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('divisao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos', to='APICredMind.cnaedivisao')),
                ('secao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos', to='APICredMind.cnaesecao')),
            ],
            options={
                'db_table': 'CnaeGrupos',
            },
        ),
        migrations.AddField(
            model_name='cnaedivisao',
            name='secao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divisoes', to='APICredMind.cnaesecao'),
        ),
        migrations.CreateModel(
            name='CnaeClasse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('divisao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='APICredMind.cnaedivisao')),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='APICredMind.cnaegrupo')),
                ('secao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='APICredMind.cnaesecao')),
            ],
            options={
                'db_table': 'CnaeClasses',
            },
        ),
        migrations.CreateModel(
            name='CnaeSubclasse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subclasses', to='APICredMind.cnaeclasse')),
                ('divisao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subclasses', to='APICredMind.cnaedivisao')),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subclasses', to='APICredMind.cnaegrupo')),
                ('secao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subclasses', to='APICredMind.cnaesecao')),
            ],
            options={
                'db_table': 'CnaeSubclasses',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='cnaegrupo',
            index=models.Index(fields=['divisao', 'secao'], name='CnaeGrupos_divisao_2d47d1_idx'),
        ),
        migrations.AddIndex(
            model_name='cnaedivisao',
            index=models.Index(fields=['secao'], name='CnaeDivisoe_secao_i_a40d83_idx'),
        ),
        migrations.AddIndex(
            model_name='cnaeclasse',
            index=models.Index(fields=['grupo', 'divisao', 'secao'], name='CnaeClasses_grupo_i_2ea583_idx'),
        ),
        migrations.AddIndex(
            model_name='cnaesubclasse',
            index=models.Index(fields=['classe', 'grupo', 'divisao', 'secao'], name='CnaeSubclas_classe__c98188_idx'),
        ),
    ]
